#include "HttPemit.h"



Document::Document()
{
	root = createChild(false, "html");
}

Document::Document(element _root)
{
	root = _root;
}

void Document::appendChild(element parent, element child)
{

}

element Document::createChild(bool closureType, const char *tag) 
{
	element newElement;
	
	newElement.tag = (char *)tag;
	newElement.closureType = closureType;
	newElement.parent = &newElement;

	return newElement;
}

element Document::createChild(bool closureType, const char *tag, attr *attributes, int attributeCount) 
{
	element newElement;

	newElement.tag = (char *)tag;
	newElement.closureType = closureType;
	newElement.attributes = attributes;
	newElement.attributeCount = attributeCount;

	return newElement;
}


element Document::createChild(const char *tag, const char *innerHtml) 
{
	element newElement;

	newElement.tag = (char *)tag;
	newElement.innerHTML = (char *)innerHtml;
	newElement.closureType = false;

	return newElement;
}


element Document::createChild(const char *tag, const char *innerHtml, attr *attributes, int attributeCount) 
{
	element newElement;

	newElement.tag = (char *)tag;
	newElement.innerHTML = (char *)innerHtml;
	newElement.attributes = attributes;
	newElement.attributeCount = attributeCount;
	newElement.closureType = false;

	return newElement;

}



element Document::createChild(element parent, bool closureType, const char *tag) 
{
	return createChild(false, "test");
}


element Document::createChild(element parent, bool closureType, const char *tag, attr *attributes, int attributeCount) 
{
	return createChild(false, "test");
}


element Document::createChild(element parent, const char *tag, const char *innerHtml, attr *attributes, int attributeCount) 
{
	return createChild(false, "test");
}


element Document::createChild(element parent, const char *tag, const char *innerHtml) 
{
	return createChild(false, "test");
}








/* Autogenerated GRACP file.
 * Auth: Rafael de Bie
 */


